name: CI
on: [push]
  # push:
  #   branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm install -g @angular/cli
    - run: ng build --prod
